name: LP-Core
version: 2.0.6.71
main: com.licker2689.lpc.LPCore
api-version: 1.16
authors: [ LICKER2689 ]
loadbefore:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib
  - LP-LegendaryCash
  - LP-VirtualStorage
  - LP-SimplePrefix
commands:
  lpc:
description: this plugin is include AnvilGUI from https://github.com/WesJD/AnvilGUI
