name: LPP-Core
version: 2.0.6.68
main: com.licker2689.lppc.LPPCore
api-version: 1.18
authors: [LICKER2689]
loadbefore:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib
  - DP-LegendaryCash
  - DP-VirtualStorage
  - DP-SimplePrefix
commands:
  lppc:
description: this plugin is include AnvilGUI from https://github.com/WesJD/AnvilGUI
